CREATE DATABASE IF NOT EXISTS INSIGHTIQ;
USE DATABASE INSIGHTIQ;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS BUSINESS;
CREATE SCHEMA IF NOT EXISTS QUALITY;
CREATE SCHEMA IF NOT EXISTS OPERATIONS;

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID INTEGER, CUSTOMER_NAME VARCHAR, REGION_CODE VARCHAR,
    CHANNEL VARCHAR, CREATED_AT DATE
);
CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID INTEGER, PRODUCT_NAME VARCHAR, CATEGORY VARCHAR, UNIT_PRICE NUMBER(12,2)
);
CREATE OR REPLACE TABLE RAW.ORDERS (
    ORDER_ID INTEGER, CUSTOMER_ID INTEGER, ORDER_DATE DATE, ORDERED_AT TIMESTAMP_NTZ,
    CHANNEL VARCHAR, ORDER_STATUS VARCHAR, ORDER_TOTAL NUMBER(12,2)
);
CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    ORDER_ITEM_ID INTEGER, ORDER_ID INTEGER, PRODUCT_ID INTEGER, QUANTITY INTEGER,
    UNIT_PRICE NUMBER(12,2), LINE_TOTAL NUMBER(12,2)
);
CREATE OR REPLACE TABLE RAW.WEB_TRAFFIC (
    TRAFFIC_DATE DATE, SESSIONS INTEGER, CHECKOUT_SESSIONS INTEGER
);
CREATE OR REPLACE TABLE RAW.PAYMENTS (
    PAYMENT_ATTEMPT_ID VARCHAR, ORDER_ID INTEGER, PAYMENT_DATE DATE,
    STATUS VARCHAR, AMOUNT NUMBER(12,2)
);
CREATE OR REPLACE TABLE RAW.PUBLIC_ONLINE_RETAIL (
    INVOICE_NO VARCHAR, STOCK_CODE VARCHAR, DESCRIPTION VARCHAR, QUANTITY INTEGER,
    INVOICE_DATE TIMESTAMP_NTZ, UNIT_PRICE FLOAT, CUSTOMER_ID VARCHAR,
    COUNTRY VARCHAR, REVENUE FLOAT
);

CREATE OR REPLACE TABLE OPERATIONS.DEPLOYMENTS (
    DEPLOYMENT_ID VARCHAR, SERVICE VARCHAR, DEPLOYED_AT TIMESTAMP_NTZ,
    SUMMARY VARCHAR, STATUS VARCHAR
);
CREATE OR REPLACE TABLE OPERATIONS.PIPELINE_RUNS (
    RUN_ID VARCHAR, PIPELINE VARCHAR, STARTED_AT TIMESTAMP_NTZ,
    COMPLETED_AT TIMESTAMP_NTZ, STATUS VARCHAR, ROWS_WRITTEN INTEGER,
    ERROR_MESSAGE VARCHAR
);
CREATE OR REPLACE TABLE OPERATIONS.SCHEMA_CHANGES (
    CHANGE_ID VARCHAR, DEPLOYMENT_ID VARCHAR, OBJECT_NAME VARCHAR,
    COLUMN_NAME VARCHAR, CHANGE_DESCRIPTION VARCHAR, CHANGED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE OPERATIONS.DATA_DEPENDENCIES (
    DOWNSTREAM_OBJECT VARCHAR, UPSTREAM_OBJECT VARCHAR, DEPENDENCY_ORDER INTEGER,
    RELATIONSHIP VARCHAR, FILTER_LOGIC VARCHAR
);
CREATE OR REPLACE TABLE OPERATIONS.INCIDENTS (
    INCIDENT_ID VARCHAR, TITLE VARCHAR, CATEGORY VARCHAR, CONTENT VARCHAR,
    CREATED_AT TIMESTAMP_NTZ, RESOLVED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE OPERATIONS.DOCUMENTS (
    DOCUMENT_ID VARCHAR, TITLE VARCHAR, CATEGORY VARCHAR, CONTENT VARCHAR,
    CREATED_AT TIMESTAMP_NTZ
);
